### ISSUE TITLE
Please post builds

### ISSUE THREAD

**Issue by bennytheshap** [sgithens/boxer-sunrise#2]
Thank you for presenting at PPIG.
Would you be open to posting binary builds here?

**Comment by bennytheshap** [comment]
Ah, never mind, I see you have. Thank you!

**Comment by sgithens** [comment]
@bennytheshap Thanks for the interest! You've found them! I hope to have another build within the week with the improved font you say during PPIG today, which should make quite a difference.  You can be sure that things are still a bit buggy at this early stage, so hopefully you can bear with us as we try to get as many annoyances fixed as soon as possible.

Cheers!
